### PR TITLE
Fix python router logic

### LINKED ISSUE #2163: UDP Router using python interface does not disconnect
**Describe the bug**
When using a router with the Python UDP interface openc3/interfaces/udp_interface.py, selecting disconnect causes it to briefly disconnect then automatically reconnect. This does not happen when using ruby interfaces.

**To Reproduce**
1. Modify the docker compose file to expose the following ports:
```
openc3-operator:
    user: "${OPENC3_USER_ID:-1001}:${OPENC3_GROUP_ID:-1001}"
    image: "${OPENC3_REGISTRY}/${OPENC3_NAMESPACE}/openc3-operator${OPENC3_IMAGE_SUFFIX}:${OPENC3_TAG}"
    restart: "unless-stopped"
    ports:
    #   - "127.0.0.1:7779:7779" # Open port for the demo router
    #   - "127.0.0.1:8081:8081/udp" # Open a udp port
      - "7779:7779/udp"
      - "8081:8081/udp"
```

2. Modify plugin.txt like this (target names and addresses have been changed):
```
TARGET BOB <%= bob_target_name %>
INTERFACE <%= bob_target_name %>_INT openc3/interfaces/udp_interface.py 172.17.0.1 8081 8081
  MAP_TARGET <%= bob_target_name %>

ROUTER TEAL_ROUTER openc3/interfaces/udp_interface.py 172.17.0.15 7779 7779
  MAP_TARGET <%= bob_target_name %>
```

3. Build the plugin - openc3.sh cli rake build VERSION=0.0.1
4. Open Cosmos in a browser
5. Navigate to the Admin Console and install the plugin
6. Navigate to the CmdTlmServer page and select the 'Routers' tab
7. Select 'Disconnect' 
8. The Router disconnects then reconnects

**Expected behavior**
The Router should not reconnect

**Log Messages**
```
The log messages produce the following error. I am unsure if it is directly related to this issue.
Unexpected process died... respawning! python router_microservice.py DEFAULT__ROUTER__TEAL_ROUTER
Stdout:
{"time":1750779430591545739,"@timestamp":"2025-06-24T15:37:10.591545Z","level":"INFO","microservice_name":"DEFAULT__ROUTER__TEAL_ROUTER","container_name":"42cb7443f325","message":"Microservice initialized with config:
{\"name\"=>\"DEFAULT__ROUTER__TEAL_ROUTER\", \"folder_name\"=>nil, \"cmd\"=>[\"python\", \"router_microservice.py\", \"DEFAULT__ROUTER__TEAL_ROUTER\"], \"work_dir\"=>\"/openc3/python/openc3/microservices\", \"ports\"=>[], \"env\"=>{}, \"topics\"=>[], \"target_names\"=>[\"EWS_SAT\"], \"options\"=>[], \"parent\"=>nil, \"container\"=>nil, \"updated_at\"=>1750779329848795628, \"plugin\"=>\"openc3-cosmos-ews-sat-0.0.7.gem__20250624153527\", \"needs_dependencies\"=>true, \"secrets\"=>[], \"prefix\"=>nil, \"disable_erb\"=>nil, \"ignore_changes\"=>nil, \"shard\"=>0, \"enabled\"=>true}","type":"log"}
{"time": 1750779431042753024, "@timestamp": "2025-06-24T15:37:11.042753Z", "level": "INFO", "microservice_name": "DEFAULT__ROUTER__TEAL_ROUTER", "container_name": "42cb7443f325", "message": "Microservice initialized with config:
{'name': 'DEFAULT__ROUTER__TEAL_ROUTER', 'folder_name': None, 'cmd': ['python', 'router_microservice.py', 'DEFAULT__ROUTER__TEAL_ROUTER'], 'work_dir': '/openc3/python/openc3/microservices', 'ports': [], 'env': {}, 'topics': [], 'target_names': ['EWS_SAT'], 'options': [], 'parent': None, 'container': None, 'updated_at': 1750779329848795628, 'plugin': 'openc3-cosmos-ews-sat-0.0.7.gem__20250624153527', 'needs_dependencies': True, 'secrets': [], 'prefix': None, 'disable_erb': None, 'ignore_changes': None, 'shard': 0, 'enabled': True}", "type": "log"}
{"time": 1750779431162703872, "@timestamp": "2025-06-24T15:37:11.162704Z", "level": "INFO", "microservice_name": "DEFAULT__ROUTER__TEAL_ROUTER", "container_name": "42cb7443f325", "message": "Retrieving DEFAULT/target_archives/EWS_SAT/EWS_SAT_current.zip from targets bucket", "type": "log"}
{"time": 1750779431170862848, "@timestamp": "2025-06-24T15:37:11.170863Z", "level": "INFO", "microservice_name": "DEFAULT__ROUTER__TEAL_ROUTER", "container_name": "42cb7443f325", "message": "Processing python target definition in file '/tmp/tmpmz2zmeu7/targets/EWS_SAT/target.txt'", "type": "log"}
{"time": 1750779431175663104, "@timestamp": "2025-06-24T15:37:11.175663Z", "level": "INFO", "microservice_name": "DEFAULT__ROUTER__TEAL_ROUTER", "container_name": "42cb7443f325", "message": "TEAL_ROUTER: Starting packet reading", "type": "log"}
{"time": 1750779431175848960, "@timestamp": "2025-06-24T15:37:11.175849Z", "level": "INFO", "microservice_name": "DEFAULT__ROUTER__TEAL_ROUTER", "container_name": "42cb7443f325", "message": "TEAL_ROUTER: Connect 192.168.0.15:7779 (write dest port) 192.168.0.15:7779 (read)", "type": "log"}
{"time": 1750779431176284928, "@timestamp": "2025-06-24T15:37:11.176285Z", "level": "INFO", "microservice_name": "DEFAULT__ROUTER__TEAL_ROUTER", "container_name": "42cb7443f325", "message": "TEAL_ROUTER: Connection Success", "type": "log"}
{"time": 1750780296284729856, "@timestamp": "2025-06-24T15:51:36.284730Z", "level": "INFO", "microservice_name": "DEFAULT__ROUTER__TEAL_ROUTER", "container_name": "42cb7443f325", "message": "TEAL_ROUTER: Disconnect requested", "type": "log"}
{"time": 1750780296285267200, "@timestamp": "2025-06-24T15:51:36.285267Z", "level": "INFO", "microservice_name": "DEFAULT__ROUTER__TEAL_ROUTER", "container_name": "42cb7443f325", "message": "TEAL_ROUTER: read_interface requested disconnect", "type": "log"}
{"time": 1750780296285323008, "@timestamp": "2025-06-24T15:51:36.285323Z", "level": "INFO", "microservice_name": "DEFAULT__ROUTER__TEAL_ROUTER", "container_name": "42cb7443f325", "message": "TEAL_ROUTER: Internal disconnect requested (returned None)", "type": "log"}
{"time": 1750780296285345024, "@timestamp": "2025-06-24T15:51:36.285345Z", "level": "INFO", "microservice_name": "DEFAULT__ROUTER__TEAL_ROUTER", "container_name": "42cb7443f325", "message": "TEAL_ROUTER: Connection Lost", "type": "log"}
{"time": 1750780296291975936, "@timestamp": "2025-06-24T15:51:36.291976Z", "level": "INFO", "microservice_name": "DEFAULT__ROUTER__TEAL_ROUTER", "container_name": "42cb7443f325", "message": "TEAL_ROUTER: shutdown requested", "type": "log"}
{"time": 1750780296292072960, "@timestamp": "2025-06-24T15:51:36.292073Z", "level": "INFO", "microservice_name": "DEFAULT__ROUTER__TEAL_ROUTER", "container_name": "42cb7443f325", "message": "TEAL_ROUTER: stop requested", "type": "log"}
{"time": 1750780296294064128, "@timestamp": "2025-06-24T15:51:36.294064Z", "level": "INFO", "microservice_name": "DEFAULT__ROUTER__TEAL_ROUTER", "container_name": "42cb7443f325", "message": "TEAL_ROUTER: Stopped packet reading", "type": "log"}
{"time": 1750780296294411008, "@timestamp": "2025-06-24T15:51:36.294411Z", "level": "INFO", "microservice_name": "DEFAULT__ROUTER__TEAL_ROUTER", "container_name": "42cb7443f325", "message": "Shutting down microservice: DEFAULT__ROUTER__TEAL_ROUTER", "type": "log"}

Stderr: Environment (please complete the following information):

```

**Environment (please complete the following information):**

OS: Kubuntu 24.10
OpenC3 COSMOS Version 6.5
Browser: Firefox

### PR DESCRIPTION
**Pull request by jmthomas**
closes #2163

### CODE REVIEW

File: openc3/lib/openc3/microservices/interface_microservice.rb [hunk 1]
```diff
@@ -288,14 +290,13 @@ def run
...
               if hazardous or restricted or (@critical_commanding == 'ALL' and manual)
+                cmd_type = 'NORMAL'
                 if hazardous
-                  type = 'HAZARDOUS'
+                  cmd_type = 'HAZARDOUS'
                 elsif restricted
-                  type = 'RESTRICTED'
-                else
-                  type = 'NORMAL'
+                  cmd_type = 'RESTRICTED'
```
Comment (jmthomas) [inline openc3/lib/openc3/microservices/interface_microservice.rb:297]: Renamed to match python

File: openc3/lib/openc3/microservices/interface_microservice.rb [hunk 2]
```diff
@@ -428,10 +429,12 @@ def run
               params = JSON.parse(msg_hash['params'], allow_nan: true, create_additions: true)
             end
             @router = @tlm.attempting(*params)
+            next 'SUCCESS'
           end
           if msg_hash['disconnect']
             @logger.info "#{@router.name}: Disconnect requested"
             @tlm.disconnect(false)
+            next 'SUCCESS'
```
Comment (jmthomas) [inline openc3/lib/openc3/microservices/interface_microservice.rb:437]: Not sure how this worked without the `next 'SUCCESS'` but this matches the rest of the behavior

File: openc3/python/openc3/microservices/interface_microservice.py [hunk 3]
```diff
@@ -299,16 +316,14 @@ def process_cmd(self, topic, msg_id, msg_hash, redis):
             if self.critical_commanding is not None and self.critical_commanding != "OFF" and not release_critical:
                 restricted = command.restricted
                 if hazardous or restricted or (self.critical_commanding == "ALL" and manual):
-                    type = None
+                    cmd_type = "NORMAL"
```
Comment (jmthomas) [inline openc3/python/openc3/microservices/interface_microservice.py:319]: `type` is a built-in in Python so renamed

File: openc3/python/openc3/microservices/interface_microservice.py [hunk 4]
```diff
@@ -413,7 +428,11 @@ def graceful_kill(self):
         time.sleep(0.001)  # Allow other threads to run
 
     def run(self):
-        for topic, msg_id, msg_hash, redis in RouterTopic.receive_telemetry(self.router, scope=self.scope):
+        generator = RouterTopic.receive_telemetry(self.router, scope=self.scope)
+        topic, msg_id, msg_hash, _redis = next(generator)
```
Comment (jmthomas) [inline openc3/python/openc3/microservices/interface_microservice.py:432]: This being inside of a `for` loop meant that the old `return` statements would break the loop and cause the thread to exit which was detected by the operator and then restarted and immediately would reconnect. This was the source of the bug.

File: openc3/python/openc3/microservices/interface_microservice.py [hunk 5]
```diff
@@ -438,35 +459,42 @@ def run(self):
                 if msg_hash.get(b"shutdown"):
                     self.logger.info(f"{self.router.name}: Shutdown requested")
                     RouterTopic.clear_topics(RouterTopic.topics(self.router, scope=self.scope))
-                    return
-                if msg_hash.get(b"connect"):
+                    result = "SHUTDOWN"
```
Comment (jmthomas) [inline openc3/python/openc3/microservices/interface_microservice.py:462]: `SHUTDOWN` is the only return code that breaks the loop

File: openc3/python/openc3/models/interface_model.py [hunk 6]
```diff
@@ -192,7 +193,7 @@ def build(self):
             interface_or_router.add_protocol(klass, protocol[2:], protocol[0].upper())
         if self.log_stream:
             interface_or_router.stream_log_pair = StreamLogPair(interface_or_router.name, self.log_stream)
-            interface_or_router.start_raw_logging
+            interface_or_router.start_raw_logging()
```
Comment (jmthomas) [inline openc3/python/openc3/models/interface_model.py:196]: Bug fix

File: openc3/python/openc3/microservices/interface_microservice.py [hunk 7]
```diff
@@ -438,35 +459,42 @@ def run(self):
...
+                        self.tlm.disconnect(False)
+                        result = "SUCCESS"
+                    except Exception as e:
+                        self.logger.error(f"{self.router.name}: disconnect: {traceback.format_exc()}")
+                        result = str(e)
+                elif msg_hash.get(b"log_stream"):
                     if msg_hash[b"log_stream"].decode() == "true":
                         self.logger.info(f"{self.router.name}: Enable stream logging")
-                        self.router.start_raw_logging
+                        self.router.start_raw_logging()
```
Comment (jmthomas) [inline openc3/python/openc3/microservices/interface_microservice.py:481]: bug fix

File: openc3/python/openc3/microservices/interface_microservice.py [hunk 8]
```diff
@@ -438,35 +459,42 @@ def run(self):
...
                     else:
                         self.logger.info(f"{self.router.name}: Disable stream logging")
-                        self.router.stop_raw_logging
-                if msg_hash.get(b"router_cmd"):
+                        self.router.stop_raw_logging()
```
Comment (jmthomas) [inline openc3/python/openc3/microservices/interface_microservice.py:484]: bug fix

File: openc3/lib/openc3/microservices/interface_microservice.rb (hunk 1 above)
Comment (mcosgriff) [reply openc3/lib/openc3/microservices/interface_microservice.rb:297]: Can cmd_type be made into an enum?

File: openc3/python/pyproject.toml [hunk 9]
```diff
@@ -37,6 +37,7 @@ fakeredis = "^2.31"
 pytest = "^8.3"
 ruff = "^0.14"
 pytest-profiling = "^1.8"
+pylint = "^4.0.2"
```
Comment (mcosgriff) [inline openc3/python/pyproject.toml:40]: What does pylint provide us that ruff doesn't already?

File: openc3/python/poetry.lock
Comment (mcosgriff) [inline openc3/python/poetry.lock:1]: When are we moving to uv ;)

File: openc3/python/pyproject.toml (hunk 9 above)
Comment (jmthomas) [reply openc3/python/pyproject.toml:40]: well it found all the places I forgot to add `()` to the method call!

File: openc3/python/poetry.lock
Comment (jmthomas) [reply openc3/python/poetry.lock:1]: Whenever you create the PR ;)
