### PR TITLE
Array item bugs

### LINKED ISSUE #3238: "Graph" context menu option on value widgets does not work for indexed array items
### Describe the bug

Right clicking on a value widget and clicking "Graph" does not pass the index for indexed array items to TlmGrapher. It just passes the whole array, which results in nothing graphed:
Image

### To Reproduce

1. Create a tlmviewer screen with this content:
```
SCREEN AUTO AUTO 1.0
VALUE INST2 HEALTH_STATUS ARY[0]
```
2. Save and view the screen
3. Right click on the value widget and click "Graph"
4. TlmGrapher opens, but the graph contains `INST2 HEALTH_STATUS ARY` instead of `INST2 HEALTH_STATUS ARY[0]`

### Expected behavior

Array index is included in item passed to tlmgrapher

### Screenshots

_No response_

### OS

all

### OpenC3 COSMOS Version

7.0.0

### Browser

all

### LINKED ISSUE #3248: Tlm Viewer graph cannot graph array items
### Describe the bug

Graphing array items works in Tlm Grapher, but not Tlm Viewer. The graph just shows nothing:
Image

### To Reproduce

1. Create a TlmViewer screen with a definition like:
```
SCREEN AUTO AUTO 1.0

LABELVALUEDESC INST HEALTH_STATUS ARY
LABELVALUEDESC INST HEALTH_STATUS ARY[0] "ARY[0]"
LABELVALUEDESC INST HEALTH_STATUS ARY[1] "ARY[1]"
LABELVALUEDESC INST HEALTH_STATUS ARY[2] "ARY[2]"
LINEGRAPH INST HEALTH_STATUS ARY[0]
  SETTING ITEM INST HEALTH_STATUS ARY[1]
  SETTING ITEM INST HEALTH_STATUS ARY[2]
```

### Expected behavior

Indexed array items are graphed

### Screenshots

_No response_

### OS

all

### OpenC3 COSMOS Version

7.0.0

### Browser

all

### PR DESCRIPTION
**Pull request by ryan-pratt**
closes #3238 
closes #3248

### CODE REVIEW

File: openc3-cosmos-init/plugins/packages/openc3-vue-common/src/widgets/VWidget.js [hunk 1]
```diff
@@ -163,12 +154,25 @@ export default {
...
+      }
+      return url + '/'
+    },
   },
   created() {
     // If they're not passing us the value and limitsState we have to register
     if (this.value === null || this.limitsState === null) {
       // Remove double bracket escaping. This means they actually have an item
       // with a bracket in the name, not an array index.
+      console.log('before: ' + this.parameters)
```
Comment (clayandgen) [inline openc3-cosmos-init/plugins/packages/openc3-vue-common/src/widgets/VWidget.js]: Remove?

**Review by clayandgen — APPROVED** [review]
Tested both of the issues, and the results look good.
Minor items:
- Remove `console.log`
- Run `eslint` to fix linter error
