### PR TITLE
script support scope for all methods

### LINKED ISSUE #13: Scheduling a command in Calendar doesn't work
Scheduled "INST ABORT" command (simple no parameters) and resulted in:
```
TVAC run_cmd failed > {"name"=>"TVAC", "updated_at"=>1658442615446107134, "fulfillment"=>false, "duration"=>180, "start"=>1658442696, "stop"=>1658442876, "kind"=>"command", "events"=>[{"time"=>1658442321, "event"=>"created"}, {"time"=>1658442456, "event"=>"queued"}, {"time"=>1658442458, "event"=>"failed", "commit"=>true, "message"=>"Packet 'INST ABORT {\"scope\"=>\"DEFAULT\"}' does not exist"}, {"time"=>1658442615, "event"=>"updated"}, {"time"=>1658442696, "event"=>"queued"}, {"time"=>1658442696, "event"=>"failed", "commit"=>true, "message"=>"Packet 'INST ABORT {\"scope\"=>\"DEFAULT\"}' does not exist"}], "data"=>{"environment"=>[], "command"=>"INST ABORT"}}, Packet 'INST ABORT {"scope"=>"DEFAULT"}' does not exist
```

### LINKED ISSUE #15: All Ruby API calls should support scope and token arguments

### PR DESCRIPTION
**Pull request by ryanmelt**
closes #13 
closes #15

### CODE REVIEW

File: openc3/lib/openc3/script/limits.rb [hunk 1]
```diff
@@ -23,17 +23,18 @@ module Script
 
     # Define all the modification methods such that we can disconnect them
     %i(enable_limits disable_limits set_limits enable_limits_group disable_limits_group set_limits_set).each do |method_name|
-      define_method(method_name) do |*args|
+      define_method(method_name) do |*args, **kw_args, &block|
```
Comment (jmthomas) [inline openc3/lib/openc3/script/limits.rb:26]: Do any of these actually take a block?

**Review by jmthomas — COMMENTED** [review]
Wow I'm glad you tackled this one!

File: openc3/lib/openc3/script/limits.rb (hunk 1 above)
Comment (ryanmelt) [reply openc3/lib/openc3/script/limits.rb:26]: Don't know.  But if they do it will work now.
