### PR TITLE
Fix linegraph widget and add sparkline

### LINKED ISSUE #44: Graph widget doesn't hide overview
The graph widget in TlmViewer doesn't hide the overview and instead applies the full height of the main graph resulting in effectively a duplicate graph.

In addition it doesn't appear to be scaling correctly. For example, try graphing INST ADCS POSX.

### LINKED ISSUE #47: Sparkline widget for simple graph
This might be achievable simply using the LINEWIDGET but I'd like something even simpler which hides everything except a simple line graph. Probably no legend and maybe just a label in front identifying the value. This is pretty common in other C3 systems.

### PR DESCRIPTION
**Pull request by jmthomas**
closes #44
closes #47

### CODE REVIEW

File: openc3-init/plugins/packages/openc3-tool-tlmviewer/src/tools/TlmViewer/Openc3Screen.vue [hunk 1]
```diff
@@ -409,17 +419,15 @@ export default {
       this.screenKey = Math.floor(Math.random() * 1000000)
       // After re-render wait and see if there are errors before saving
       this.$nextTick(function () {
-        if (this.errors.length === 0) {
```
Comment (jmthomas) [inline openc3-init/plugins/packages/openc3-tool-tlmviewer/src/tools/TlmViewer/Openc3Screen.vue:412]: Sometimes I was getting errors from I think TEMP2 due to the nil / undefined return values. This prevented saving the screen. I think it's better to let them save the screen no matter what and the error messages still identify what's going on.

**Review by ryanmelt — APPROVED** [review]
