### PR TITLE
Queue binary

### LINKED ISSUE #2520: Buggy behavior with Editable Cmd History in Cmd Sender for (cmd validation)
COSMOS v6.9.2

The toggle for "Disable Command Validation" overrides whatever is sent with Editable Cmd History

Case 1 
- Disable Command Validation toggled ON
- `cmd("BOB CMD")` from editable cmd history
    - expected: executed **with** validation
    - actual: executed **without** validation

Case 2
- Disable Command Validation toggled OFF
- `cmd("BOB CMD", validate=False)` from editable cmd history
    - expected: executed **without** validation
    - actual: executed **with** validation

The Disable Command Validation toggle is hidden behind the dropdown, so this often results in unexpected behavior

### LINKED ISSUE #2521: Editable Command History ignores queue=False
COSMOS v6.9.2

Commands sent from editable command history ignore `queue=False` arg. We have `OPENC3_DEFAULT_QUEUE` set .

Naming a queue works as expected, .e.g. `queue="DEFAULT"`

### PR DESCRIPTION
**Pull request by jmthomas**
closes #2520
closes #2521

### CODE REVIEW

File: openc3/lib/openc3/io/json_rpc.rb [hunk 1]
```diff
@@ -59,6 +59,12 @@ class String
   NON_ASCII_PRINTABLE = /[^\x21-\x7e\s]/
   NON_UTF8_PRINTABLE = /[\x00-\x08\x0E-\x1F\x7F]/
   def as_json(_options = nil)
+    # If string is ASCII-8BIT (binary) and has non-ASCII bytes (> 127), encode as binary
+    # This handles data from hex_to_byte_string and other binary sources
+    if self.encoding == Encoding::ASCII_8BIT && self.bytes.any? { |b| b > 127 }
+      return self.to_json_raw_object
+    end
```
Comment (jmthomas) [inline openc3/lib/openc3/io/json_rpc.rb:66]: This was actually important to getting a command like `cmd("INST MEMLOAD with DATA 0xDEAD")` to work

**Comment by jmthomas** [comment]
@clayandgen you need to be using this PR from Enterprise to test the changes: https://github.com/OpenC3/cosmos-enterprise/pull/362

**Review by clayandgen — CHANGES_REQUESTED** [review]
Actually sorry, I don't think the behavior for the editable command history with `queue=False` is working as intended. This puts the command back on the queue, and I have `+OPENC3_DEFAULT_QUEUE=DEFAULT` set in my .env. The change is probably for the enterprise repo

Screenshot 2025-11-24 at 9 56 29 AM

**Review by clayandgen — DISMISSED** [review]
agh sorry -- approved the wrong PR
