### PR TITLE
Set received count in interface_microservice and inject_tlm

### LINKED ISSUE #183: Packet count resets
The packet count seems to be resetting when an interface is restarted. This messes up calls like wait_check_packet which are waiting for a certain packet count.

### LINKED ISSUE #196: Received count on inject_tlm
When using inject_tlm. Encountered received count stuck at 1 based on the tlm_api line 140. 

Instead of:
 packet.received_count += 1

Suggest maybe:
  begin
    packet.received_count = CvtModel.get_item(target_name, packet_name, "RECEIVED_COUNT", type: type.intern, scope: scope) + 1
  rescue Exception => err
    packet.received_count = 1
  end

This is due to the fact that if the packet is generated with a received count of 0 so 0+=1 will always be 1.

### PR DESCRIPTION
**Pull request by jmthomas**
closes #196 
closes #183

### CODE REVIEW

File: openc3/lib/openc3/api/tlm_api.rb [hunk 1]
```diff
@@ -137,8 +137,11 @@ def inject_tlm(target_name, packet_name, item_hash = nil, type: :CONVERTED, scop
         end
       end
       packet.received_time = Time.now.sys
-      # TODO: New packet so received_count is not correct
-      packet.received_count += 1
+      begin
+        packet.received_count = CvtModel.get_item(target_name, packet_name, "RECEIVED_COUNT", type: :CONVERTED, scope: scope) + 1
```
Comment (ryanmelt) [inline openc3/lib/openc3/api/tlm_api.rb:141]: Probably should pull from the last message in the Raw topic?   That would be the most recent received_count.  There will always be a race condition with this, but the CVT doesn't get updated until after decom, so for high rate packets this will probably be behind.  (But then for high rate packets why are you using inject_tlm).  Don't know.

**Review by ryanmelt — CHANGES_REQUESTED** [review]
Maybe use Topics instead of CVT.  But also it may be ok as is.  Just think about it.

**Review by ryanmelt — APPROVED** [review]
