### PR TITLE
[Bugs] Autonomic bug updates

### LINKED ISSUE #2533: Autonomic add buttons to Enable/Disable All Triggers

### LINKED ISSUE #2553: Autonomic Reactions visual bug
**Describe the bug**
In Autonomic, when a reaction gets added to a trigger, sometimes that reaction does not appear under the "Reactions" list for the trigger (see image). The missing reactions do not appear in the JSON config file either. The reactions still run properly when their linked trigger is activated, so this is purely a visual bug.

**To Reproduce**

1. Create multiple triggers
2. Create multiple reactions, each linked to a different trigger
3. See that some of the reactions do not appear on the "Triggers" tab

**Expected behavior**
All reactions populate to the proper field on the Triggers tab (and to the JSON config file).

**Screenshots**
Image

Image

**Environment (please complete the following information):**

- OS: Ubuntu 22.04
- OpenC3 COSMOS Version 6.9.1
- Browser: Firefox

### PR DESCRIPTION
**Pull request by clayandgen**
closes #2533 
closes #2553 
closes https://github.com/OpenC3/cosmos-enterprise/issues/371
closes https://github.com/OpenC3/cosmos-enterprise/issues/365

### CODE REVIEW

File: openc3/lib/openc3/models/reaction_model.rb [hunk 1]
```diff
@@ -183,20 +183,17 @@ def validate_actions(actions)
...
-        trigger_models << model
-      end
-      if trigger_models.empty?
-        raise ReactionInputError.new "reaction must contain at least one valid trigger: #{@triggers}"
-      end
-      trigger_models.each do | trigger_model |
-        trigger_model.update_dependents(dependent: @name)
-        trigger_model.update()
+        model.update_dependents(dependent: @name)
+        model.update()
```
Comment (jmthomas) [inline openc3/lib/openc3/models/reaction_model.rb:196]: good optimization
