### PR TITLE
Fix ScriptRunner stuck in readonly with only custom roles

### LINKED ISSUE #2455: Incorrect read-only behavior in ace editor when using custom (non-default) roles with script_* permissions
**Describe the bug**
If a user is granted non-default roles (so not any of {admin, operator, viewer}), the frontend of ScriptRunner does not allow editing of the script.

**To Reproduce**

1. Create a new user and role in Keycloak. Map that role to the user. Ensure that the role is prefixed with `ALLSCOPES__` to map to OpenC3 roles.
2. Create a Role in the OpenC3 Admin Console's Role editor that corresponds to the role created in Keycloak. Grant the following permissions (at least, more can be granted): script_view, script_edit, script_run, system_set
3. Log into OpenC3 with the custom user created in step 1. Open the ScriptRunner tool.

**Expected behavior**
Because the user has been granted script_* and system_set permissions, they should be allowed to edit and save scripts in the ScriptRunner frontend.

**Actual behavior**
When a user attempts to edit (pressing a key on the keyboard with the editor focused), a tooltip shows up saying "Editing is disabled.".

After running a script, this limitation seems to go away. The same user can now edit the contents of the script within the editor, and save them back to the bucket they exist in. However, the cursor within the editor does not properly show up (`style: none` is present on the cursor object in the DOM).

Our guess when poking at this live was that there is some race/sync bug between the ace editor's reactivity to state updates with respect to the resolution of `await`ing the API call to get custom roles, as opposed to checking against default roles which does not require an API call.

**Environment**

- OS: Windows 11
- OpenC3 COSMOS 6.4.2
- Browser: Chrome

### PR DESCRIPTION
**Pull request by ryanmelt**
closes #2455

### CODE REVIEW

**Comment by ryanmelt** [comment]
This was a timing issue where mounted was finishing before created when waiting on role API calls.

File: openc3-cosmos-init/plugins/packages/openc3-vue-common/src/tools/scriptrunner/ScriptRunner.vue [hunk 1]
```diff
@@ -1118,6 +1118,17 @@ export default {
         }
       }
     },
+    readOnlyUser: function (val) {
+      if (this.editor) {
+        if (val) {
+          this.editor.setReadOnly(true)
+          this.editor.renderer.$cursorLayer.element.style.display = 'none'
```
Comment (ryan-pratt) [inline openc3-cosmos-init/plugins/packages/openc3-vue-common/src/tools/scriptrunner/ScriptRunner.vue:1125]: Could you remove all the other places where this is set based on `readOnlyUser` (e.g. lines 1242-1245)? I'm not worried about thrashing, more just code maintainability

**Review by ryan-pratt — CHANGES_REQUESTED** [review]

File: openc3-cosmos-init/plugins/packages/openc3-vue-common/src/tools/scriptrunner/ScriptRunner.vue (hunk 1 above)
Comment (ryanmelt) [reply openc3-cosmos-init/plugins/packages/openc3-vue-common/src/tools/scriptrunner/ScriptRunner.vue:1125]: It needs both.   The watcher is a noop if the editor doesn't exist yet, and in that case you still need the later lines.

Comment (ryan-pratt) [reply openc3-cosmos-init/plugins/packages/openc3-vue-common/src/tools/scriptrunner/ScriptRunner.vue:1125]: Ah, I see

**Review by ryan-pratt — APPROVED** [review]
