### PR TITLE
Unify Suite output timestamps, fix CTRF d/l

### LINKED ISSUE #2510: Suite Runner download logs as CTRF doesn't work
Specifically in Suite Runner the test report doesn't work in Python but works in Ruby.

### PR DESCRIPTION
**Pull request by jmthomas**
closes #2510

### CODE REVIEW

File: openc3-cosmos-cmd-tlm-api/app/controllers/storage_controller.rb [hunk 1]
```diff
@@ -267,11 +267,11 @@ def convert_to_ctrf(report_content)
...
-          date, time, _example = last_result.split(' ')
-          start_time = DateTime.parse("#{date} #{time}").to_time.to_f * 1000
-          date, time, example = line_clean.split(' ')
-          suite_group, name, status = example.split(':')
-          stop_time = DateTime.parse("#{date} #{time}").to_time.to_f * 1000
+          date_time, _example = last_result.split('Z:')
+          start_time = DateTime.parse("#{date_time}Z").to_time.to_f * 1000
+          date_time, example = line_clean.split('Z:')
+          suite_group, name, status = example.strip.split(':')
+          stop_time = DateTime.parse("#{date_time}Z").to_time.to_f * 1000
```
Comment (ryan-pratt) [inline openc3-cosmos-cmd-tlm-api/app/controllers/storage_controller.rb:274]: Is `date_time` always UTC here?

File: openc3/lib/openc3/script/suite_results.rb [hunk 2]
```diff
@@ -172,11 +172,11 @@ def footer
     end
 
     def write(string)
-      @report << (Time.now.sys.formatted + ': ' + string)
+      @report << (Time.now.utc.strftime("%Y-%m-%dT%H:%M:%S.%6NZ") + ': ' + string)
     end
 
     def puts(string)
-      @report << (Time.now.sys.formatted + ': ' + string)
+      @report << (Time.now.utc.strftime("%Y-%m-%dT%H:%M:%S.%6NZ") + ': ' + string)
```
Comment (ryan-pratt) [inline openc3/lib/openc3/script/suite_results.rb:179]: Shouldn't this be `%Z`? e.g: `"%Y-%m-%dT%H:%M:%S.%6N%Z"`

Comment (jmthomas) [reply openc3/lib/openc3/script/suite_results.rb:179]: I actually want the literal `Z` char. `%Z` gives the timezone so it would be `2025-11-13T17:16:52.575812UTC` instead of `2025-11-13T17:16:52.575812Z`.

File: openc3-cosmos-cmd-tlm-api/app/controllers/storage_controller.rb (hunk 1 above)
Comment (jmthomas) [reply openc3-cosmos-cmd-tlm-api/app/controllers/storage_controller.rb:274]: It is but I think we want this to reflect the system setting for timezone because otherwise you're force to look at these reports with UTC time which can be annoying if you're not used to it. Most of our customers would probably prefer to use local time unless they're on Ops.

**Review by ryan-pratt — APPROVED** [review]

File: openc3-cosmos-cmd-tlm-api/app/controllers/storage_controller.rb (hunk 1 above)
Comment (jmthomas) [reply openc3-cosmos-cmd-tlm-api/app/controllers/storage_controller.rb:274]: I looked into this and tried to call `get_setting` but that required updates to the user.acl to add `~openc3__settings` and then the local call to `Time.now.strftime("%Y-%m-%dT%H:%M:%S.%6N%z")` returns `+0000` for the timezone in the container. Long story short is that the containers are all running with UTC so since this backend only I'm just going to output UTC.
