### PR TITLE
Better cleanup and handle limits

### LINKED ISSUE #2: Removing a target should remove it from Limits Monitor
**Describe the bug**
If you delete a plugin (like the Demo) and go to Limits Monitor you will see all the out of limits items left over from the plugin's targets. Deleting the plugin and it's targets should clear the limits monitor channel in redis.

### PR DESCRIPTION
**Pull request by jmthomas**
closes #2

### CODE REVIEW

File: openc3-init/plugins/packages/openc3-tool-admin/src/tools/OpenC3Admin/tabs/PluginsTab.vue [hunk 1]
```diff
@@ -342,11 +343,14 @@ export default {
           okText: 'Delete',
           cancelText: 'Cancel',
         })
-        .then(function (dialog) {
+        .then((dialog) => {
+          this.alert = `Removing plugin ${plugin} ...`
+          this.alertType = 'success'
+          this.showAlert = true
```
Comment (jmthomas) [inline openc3-init/plugins/packages/openc3-tool-admin/src/tools/OpenC3Admin/tabs/PluginsTab.vue:349]: Removing a plugin can take a while so I wanted to notify the user that it started

File: openc3-init/plugins/packages/openc3-tool-limitsmonitor/src/tools/LimitsMonitor/LimitsControl.vue [hunk 2]
```diff
@@ -204,6 +207,27 @@ export default {
...
+    this.cable
+      .createSubscription('LimitsEventsChannel', localStorage.scope, {
+        received: (data) => {
+          const parsed = JSON.parse(data)
+          this.handleMessages(parsed)
+        },
+      })
+      .then((limitsSubscription) => {
+        this.limitsSubscription = limitsSubscription
+      })
```
Comment (jmthomas) [inline openc3-init/plugins/packages/openc3-tool-limitsmonitor/src/tools/LimitsMonitor/LimitsControl.vue:220]: Moving the subscription here is duplication of the Events subscription but greatly simplifies the design since the Events wants history

File: openc3-init/plugins/packages/openc3-tool-limitsmonitor/src/tools/LimitsMonitor/LimitsControl.vue [hunk 3]
```diff
@@ -215,17 +239,24 @@ export default {
...
+    }
+    if (this.configSubscription) {
+      this.configSubscription.unsubscribe()
+    }
+    this.cable.disconnect()
   },
   methods: {
     updateOutOfLimits() {
+      this.items = []
+      this.itemList = []
```
Comment (jmthomas) [inline openc3-init/plugins/packages/openc3-tool-limitsmonitor/src/tools/LimitsMonitor/LimitsControl.vue:253]: This method now initializes the visible list of items

File: openc3-init/plugins/packages/openc3-tool-limitsmonitor/src/tools/LimitsMonitor/LimitsControl.vue [hunk 4]
```diff
@@ -307,13 +338,22 @@ export default {
     },
     update() {
       if (this.$store.state.tlmViewerItems.length !== 0) {
+        // localStorage.axiosIgnoreResponse = '500' // localStorage only supports strings
```
Comment (jmthomas) [inline openc3-init/plugins/packages/openc3-tool-limitsmonitor/src/tools/LimitsMonitor/LimitsControl.vue:341]: This would potentially prevent popups on bad items but I think my config events handler mostly covers this now. Left it just in case as it's a useful pattern.

File: openc3-init/plugins/packages/openc3-tool-limitsmonitor/src/tools/LimitsMonitor/LimitsEvents.vue [hunk 5]
```diff
@@ -65,13 +66,39 @@ export default {
...
+        'LimitsEventsChannel',
+        localStorage.scope,
+        {
+          received: (data) => {
+            const parsed = JSON.parse(data)
+            this.handleMessages(parsed)
+          },
+        },
+        {
+          history_count: 1000,
```
Comment (jmthomas) [inline openc3-init/plugins/packages/openc3-tool-limitsmonitor/src/tools/LimitsMonitor/LimitsEvents.vue:89]: History makes this incompatible with LimitsControl

File: openc3/lib/openc3/microservices/decom_microservice.rb [hunk 6]
```diff
@@ -82,6 +82,7 @@ def decom_packet(topic, _msg_id, msg_hash, _redis)
     # @param value [Object] The current value of the item
     # @param log_change [Boolean] Whether to log this limits change event
     def limits_change_callback(packet, item, old_limits_state, value, log_change)
+      return if @cancel_thread
```
Comment (jmthomas) [inline openc3/lib/openc3/microservices/decom_microservice.rb:85]: I added this during my early debugging but I think it's a small optimization that still makes sense

File: openc3/lib/openc3/models/plugin_model.rb [hunk 7]
```diff
@@ -267,7 +267,14 @@ def as_json(*a)
 
     # Undeploy all models associated with this plugin
     def undeploy
-      [ToolModel, TargetModel, InterfaceModel, RouterModel, MicroserviceModel, WidgetModel].each do |model|
+      MicroserviceModel.find_all_by_plugin(plugin: @name, scope: @scope).each do |name, model_instance|
+        model_instance.destroy
+      end
+      # Wait for the operator to wake up and remove the microservice processes
+      sleep 30 # Cycle time 15s plus 2s wait for soft stop and then hard stop
```
Comment (jmthomas) [inline openc3/lib/openc3/models/plugin_model.rb:274]: I didn't really know the best way to signal the MicroserviceOperator that it's time to remove processes so I just left the sleep. If you want to optimize from here that would be awesome.

File: openc3/lib/openc3/models/target_model.rb [hunk 8]
```diff
@@ -442,11 +445,6 @@ def undeploy
       Store.del("#{@scope}__openc3tlm__#{@name}")
       Store.del("#{@scope}__openc3cmd__#{@name}")
 
-      # Note: these match the names of the services in deploy_microservices
-      %w(DECOM COMMANDLOG DECOMCMDLOG PACKETLOG DECOMLOG REDUCER CLEANUP).each do |type|
-        model = MicroserviceModel.get_model(name: "#{@scope}__#{type}__#{@name}", scope: @scope)
-        model.destroy if model
-      end
```
Comment (jmthomas) [inline openc3/lib/openc3/models/target_model.rb:449]: I think this is unnecessary due to the code in plugin_model undeploy

File: openc3/lib/openc3/topics/limits_event_topic.rb [hunk 9]
```diff
@@ -97,10 +97,12 @@ def self.current_set(scope:)
...
     end
 
-    def self.delete(_target_name, _packet_name, scope:)
+    def self.delete(target_name, packet_name, scope:)
       limits = Store.hgetall("#{scope}__current_limits")
       limits.each do |item, _limits_state|
-        Store.hdel("#{scope}__current_limits", item)
+        if item =~ /^#{target_name}__#{packet_name}__/
+          Store.hdel("#{scope}__current_limits", item)
+        end
```
Comment (jmthomas) [inline openc3/lib/openc3/topics/limits_event_topic.rb:105]: Previously we were just deleting everything? That's wrong so I delete based on matching the name.

File: openc3/lib/openc3/models/target_model.rb (hunk 8 above)
Comment (ryanmelt) [reply openc3/lib/openc3/models/target_model.rb:449]: Not unnecessary from a standalone perspective.  Needs to be added back.

File: openc3/lib/openc3/topics/limits_event_topic.rb (hunk 9 above)
Comment (ryanmelt) [reply openc3/lib/openc3/topics/limits_event_topic.rb:105]: Good catch

File: openc3-init/plugins/packages/openc3-tool-limitsmonitor/src/tools/LimitsMonitor/LimitsControl.vue (hunk 4 above)
Comment (ryanmelt) [reply openc3-init/plugins/packages/openc3-tool-limitsmonitor/src/tools/LimitsMonitor/LimitsControl.vue:341]: This is a global setting, so probably dangerous?

File: openc3/lib/openc3/models/plugin_model.rb (hunk 7 above)
Comment (ryanmelt) [reply openc3/lib/openc3/models/plugin_model.rb:274]: I'm going to decrease the operator cycle time to 5s and reduce this.

File: openc3/lib/openc3/models/target_model.rb (hunk 8 above)
Comment (ryanmelt) [reply openc3/lib/openc3/models/target_model.rb:449]: I will restore.

**Review by ryanmelt — CHANGES_REQUESTED** [review]
