### PR TITLE
Fix xtce_converter CLI crash with gem_name nil and PythonProxy .class

### LINKED ISSUE #2837: Recent regression in xtce_converter
**Describe the bug**
Using v6.10.1, the xtce_converter tool works fine to export my COSMOS cmd/tlm definitions to XTCE format. Running v6.10.4, it fails with the following error/traceback:

```
Error: 
NoMethodError : undefined method 'name' for an instance of String
/usr/lib/ruby/gems/3.4.0/gems/openc3-6.10.4/lib/openc3/packets/parsers/xtce_converter.rb:182:in 'block (3 levels) in OpenC3::XtceConverter#create_algorithms'
/usr/lib/ruby/gems/3.4.0/gems/openc3-6.10.4/lib/openc3/packets/parsers/xtce_converter.rb:180:in 'Hash#each'
/usr/lib/ruby/gems/3.4.0/gems/openc3-6.10.4/lib/openc3/packets/parsers/xtce_converter.rb:180:in 'block (2 levels) in OpenC3::XtceConverter#create_algorithms'
/usr/lib/ruby/gems/3.4.0/gems/nokogiri-1.19.0-x86_64-linux-musl/lib/nokogiri/xml/builder.rb:433:in 'Nokogiri::XML::Builder#insert'
/usr/lib/ruby/gems/3.4.0/gems/nokogiri-1.19.0-x86_64-linux-musl/lib/nokogiri/xml/builder.rb:415:in 'Nokogiri::XML::Builder#method_missing'
/usr/lib/ruby/gems/3.4.0/gems/openc3-6.10.4/lib/openc3/packets/parsers/xtce_converter.rb:179:in 'block in OpenC3::XtceConverter#create_algorithms'
/usr/lib/ruby/gems/3.4.0/gems/nokogiri-1.19.0-x86_64-linux-musl/lib/nokogiri/xml/builder.rb:331:in 'Nokogiri::XML::Builder#initialize'
/usr/lib/ruby/gems/3.4.0/gems/openc3-6.10.4/lib/openc3/packets/parsers/xtce_converter.rb:178:in 'Class#new'
/usr/lib/ruby/gems/3.4.0/gems/openc3-6.10.4/lib/openc3/packets/parsers/xtce_converter.rb:178:in 'OpenC3::XtceConverter#create_algorithms'
/usr/lib/ruby/gems/3.4.0/gems/openc3-6.10.4/lib/openc3/packets/parsers/xtce_converter.rb:157:in 'block (3 levels) in OpenC3::XtceConverter#initialize'
/usr/lib/ruby/gems/3.4.0/gems/nokogiri-1.19.0-x86_64-linux-musl/lib/nokogiri/xml/builder.rb:433:in 'Nokogiri::XML::Builder#insert'
/usr/lib/ruby/gems/3.4.0/gems/nokogiri-1.19.0-x86_64-linux-musl/lib/nokogiri/xml/builder.rb:415:in 'Nokogiri::XML::Builder#method_missing'
/usr/lib/ruby/gems/3.4.0/gems/openc3-6.10.4/lib/openc3/packets/parsers/xtce_converter.rb:145:in 'block (2 levels) in OpenC3::XtceConverter#initialize'
/usr/lib/ruby/gems/3.4.0/gems/nokogiri-1.19.0-x86_64-linux-musl/lib/nokogiri/xml/builder.rb:331:in 'Nokogiri::XML::Builder#initialize'
/usr/lib/ruby/gems/3.4.0/gems/openc3-6.10.4/lib/openc3/packets/parsers/xtce_converter.rb:144:in 'Class#new'
/usr/lib/ruby/gems/3.4.0/gems/openc3-6.10.4/lib/openc3/packets/parsers/xtce_converter.rb:144:in 'block in OpenC3::XtceConverter#initialize'
/usr/lib/ruby/gems/3.4.0/gems/openc3-6.10.4/lib/openc3/packets/parsers/xtce_converter.rb:128:in 'Array#each'
/usr/lib/ruby/gems/3.4.0/gems/openc3-6.10.4/lib/openc3/packets/parsers/xtce_converter.rb:128:in 'OpenC3::XtceConverter#initialize'
/usr/lib/ruby/gems/3.4.0/gems/openc3-6.10.4/lib/openc3/packets/parsers/xtce_converter.rb:51:in 'Class#new'
/usr/lib/ruby/gems/3.4.0/gems/openc3-6.10.4/lib/openc3/packets/parsers/xtce_converter.rb:51:in 'OpenC3::XtceConverter.convert'
/usr/lib/ruby/gems/3.4.0/gems/openc3-6.10.4/lib/openc3/packets/packet_config.rb:336:in 'OpenC3::PacketConfig#to_xtce'
/usr/lib/ruby/gems/3.4.0/gems/openc3-6.10.4/lib/openc3/models/target_model.rb:642:in 'OpenC3::TargetModel#deploy'
/usr/lib/ruby/gems/3.4.0/gems/openc3-6.10.4/lib/openc3/models/plugin_model.rb:332:in 'block in OpenC3::PluginModel.install_phase2'
/usr/lib/ruby/gems/3.4.0/gems/openc3-6.10.4/lib/openc3/config/config_parser.rb:218:in 'OpenC3::ConfigParser#parse_loop'
/usr/lib/ruby/gems/3.4.0/gems/openc3-6.10.4/lib/openc3/config/config_parser.rb:218:in 'OpenC3::ConfigParser#parse_file'
/usr/lib/ruby/gems/3.4.0/gems/openc3-6.10.4/lib/openc3/models/plugin_model.rb:324:in 'OpenC3::PluginModel.install_phase2'
/openc3/bin/openc3cli:168:in 'Object#xtce_converter'
/openc3/bin/openc3cli:1098:in '<main>'
/usr/lib/ruby/gems/3.4.0/gems/openc3-6.10.4/lib/openc3/config/config_parser.rb:486:in 'OpenC3::ConfigParser#parse_errors'
/usr/lib/ruby/gems/3.4.0/gems/openc3-6.10.4/lib/openc3/config/config_parser.rb:218:in 'OpenC3::ConfigParser#parse_loop'
/usr/lib/ruby/gems/3.4.0/gems/openc3-6.10.4/lib/openc3/config/config_parser.rb:218:in 'OpenC3::ConfigParser#parse_file'
/usr/lib/ruby/gems/3.4.0/gems/openc3-6.10.4/lib/openc3/models/plugin_model.rb:324:in 'OpenC3::PluginModel.install_phase2'
/openc3/bin/openc3cli:168:in 'Object#xtce_converter'
/openc3/bin/openc3cli:1098:in '<main>'
```

**To Reproduce**
The command I ran was
```bash
../openc3.sh cli xtce_converter -p my_plugin_file.gem -o ./xtce
```

From within the `openc3-cosmos-{plugin name}/` subdirectory of my COSMOS project. This works in 6.10.1, but not 6.10.4. If desired, I can also try 6.10.2 and .3 to see exactly where/which version it stopped working in (however I suspect it was 6.10.3).

**Expected behavior**
XTCE files are produced in the specified `--output` directory.

**Screenshots**

**Environment (please complete the following information):**

- OS: Alma Linux 8
- OpenC3 COSMOS Version 6.10.4
- Browser: N/A

### PR DESCRIPTION
**Pull request by jmthomas**
Two bugs prevented the xtce_converter from running via CLI:

1. plugin_model.rb: gem_name was only set when gem_file_path was nil, causing a NoMethodError on line 234 when gem_file_path was passed directly by the xtce_converter.

2. xtce_converter.rb: PythonProxy overrides .class to return a String (the Python class path) rather than a Ruby Class object, so calling .class.name on a PythonProxy conversion failed for Python-based targets like INST2.

closes #2837

### CODE REVIEW

File: openc3/lib/openc3/models/plugin_model.rb [hunk 1]
```diff
@@ -195,6 +195,8 @@ def self.install_phase2(plugin_hash, scope:, gem_file_path: nil, validate_only:
         unless gem_file_path
           gem_name = plugin_hash['name'].split("__")[0]
           gem_file_path = OpenC3::GemModel.get(gem_name)
+        else
+          gem_name = File.basename(gem_file_path)
```
Comment (clayandgen) [inline openc3/lib/openc3/models/plugin_model.rb:199]: I think I agree with SonarQube here -- if / else would be much easier to read 😅

Comment (clayandgen) [reply openc3/lib/openc3/models/plugin_model.rb:199]: This will fix a totally separate bug I've noticed -- the `openc3cli validate` fails if `public/` is in the directory list, but this will fix that issue.

> Without public in the gemspec, the gem doesn't contain public/store_img.png. So line 232 (File.exist?) is false, img_path stays nil, and line 234's if img_path guard prevents the nil .split from ever executing.
