### PR TITLE
Script runner messages scroll

### LINKED ISSUE #1852: Script Runner log messages are cut off
First check out our main documentation site at [https://openc3.com](https://openc3.com).

**Describe the bug**
Script runner logs get cut off at the bottom after a certain number of lines

**To Reproduce**
1. Go to Script Runner
2. Execute a script that generates ~30 lines of log messages
3. Scroll as far down in the log messages as you can
4. Observe the last few lines are not viewable. The exact number of lines missing depends on the viewport height

**Expected behavior**
All log messages should be viewable

**Screenshots**
vh=1327px
Image

vh=634px
Image

**Environment (please complete the following information):**

- OS: [e.g. Windows 10, Mac OS 10.13]
- OpenC3 COSMOS Version [e.g. 5.0.6] - 6.0.2
- Browser: [e.g. Chrome, Firefox, Safari, Edge] - Chrome

### PR DESCRIPTION
**Pull request by EmilyRagan**
closes #1852
closes OpenC3/cosmos-enterprise#233

I tested this with the `inline` prop set to true as well, even though I'm not sure if that is used anywhere yet.

### CODE REVIEW

File: openc3-cosmos-init/plugins/packages/openc3-vue-common/src/tools/scriptrunner/ScriptLogMessages.vue [hunk 1]
```diff
@@ -68,10 +68,9 @@
         @click="clearLog"
       />
     </v-card-title>
-    <v-card-text>
+    <v-card-text style="overflow: auto">
```
Comment (clayandgen) [inline openc3-cosmos-init/plugins/packages/openc3-vue-common/src/tools/scriptrunner/ScriptLogMessages.vue]: Is it worth using Vuetify's [overflow](https://vuetifyjs.com/en/styles/overflow/) and [sizing](https://vuetifyjs.com/en/styles/sizing/#usage) built-in classes? I generally avoid `style` and setting custom CSS. Vuetify has built-in classes for overflow, height, and display!
