### PR TITLE
Better check message and help with NameError

### LINKED ISSUE #8: Better debugging info for NameError: uninitialized constant
If you accidentally compare a state and forget the quotes you get a NameError exception. For example:

`wait_check("INST HEALTH_STATUS COLLECT_TYPE == NORMAL", 5)`

Results in:

`NameError: uninitialized constant OpenC3::ApiShared::NORMAL`

We could capture this exception and write something a little more user friendly like:

`Uninitialized constant NORMAL. Did you mean 'NORMAL'? (String)`

Or something to that effect to help with debugging.

### PR DESCRIPTION
**Pull request by jmthomas**
closes #8

### CODE REVIEW

File: openc3/lib/openc3/script/api_shared.rb [hunk 1]
```diff
@@ -726,6 +728,12 @@ def _openc3_script_wait_implementation(target_name, packet_name, item_name, valu
       end
 
       return false, value
+    rescue NameError => error
+      if error.message =~ /uninitialized constant OpenC3::ApiShared::(\w+)/
```
Comment (jmthomas) [inline openc3/lib/openc3/script/api_shared.rb:732]: Will this still work with your Cosmos compatibility layer?

Comment (ryanmelt) [reply openc3/lib/openc3/script/api_shared.rb:732]: No but probably ok.  However make sure you preserver the stack trace when raising a new error.
