### PR TITLE
Refresh tokens 60 seconds before expire

### LINKED ISSUE #142: Server Response 500 Error when server is under heavy command load
Hello,

When running scripts with a lot of cmd or tlm api calls, the script will halt with a "No Response from Server 500 Error". this has not been observed on previous version that we have run on OpenC3. Unfortunately, when this script halts and it is a subscript, when the "GO" button is hit, it exits and the parent script continues, which can be hazardous for operational/functional capabilities if the previous script has not exited in an expected manner.

Apologies for the low quality, but here is an example of said error:
image

Thanks,

Dakota

### PR DESCRIPTION
**Pull request by ryanmelt**
closes #142

### CODE REVIEW

File: openc3-cmd-tlm-api/app/controllers/api_controller.rb [hunk 1]
```diff
@@ -58,9 +58,22 @@ def api
...
+        status, content_type, body = handle_post(request_data, request_headers)
+      rescue OpenC3::AuthError => error
+        error_code = JsonRpcError::ErrorCode::AUTH_ERROR
+        response = JsonRpcErrorResponse.new(
+          JsonRpcError.new(error_code, error.message, error), request.id
+        )
+        status = 401
+        content_type = "application/json-rpc"
+        body = response.to_json(:allow_nan => true)
+      end
```
Comment (jmthomas) [inline openc3-cmd-tlm-api/app/controllers/api_controller.rb:76]: So you're rescuing AuthErrors and explicitly setting the response. This will aid debugging but doesn't fix any issues with authentication.

File: openc3/lib/openc3/utilities/authentication.rb [hunk 2]
```diff
@@ -112,8 +114,8 @@ def _refresh_token(current_time)
       oath = _make_request(headers, data)
       @token = oath["access_token"]
       @refresh_token = oath["refresh_token"]
-      @expires_at = current_time + oath["expires_in"]
-      @refresh_expires_at = current_time + oath["refresh_expires_in"]
+      @expires_at = current_time + oath["expires_in"] - REFRESH_OFFSET_SECONDS
+      @refresh_expires_at = current_time + oath["refresh_expires_in"] - REFRESH_OFFSET_SECONDS
```
Comment (jmthomas) [inline openc3/lib/openc3/utilities/authentication.rb:118]: Ahh we were previously letting the token go right down to the wire and then recreating? Do you think this resulted in a single bad un-authenticated request before the token was regenerated? Does this still have an issue where by if you don't make a request within 60s of the token expiring it will result in a single failure?
