### PR TITLE
Fix ScriptRunner handling crashed state

### LINKED ISSUE #2534: Python ScriptRunner Execute Selection and Run From Line Not Working when stopped
They are also leaving ScriptRunner in a weird sort of running state.

### PR DESCRIPTION
**Pull request by jmthomas**
closes #2534

This would replace #2552 which had good ideas but I wanted to disallow retry for a crashed script ... it doesn't make sense to retry because unless you modify the script it will continue to crash. Also I wanted to explicitly handle all the script states in the case statement (spawning and init were not handled).

### CODE REVIEW

File: openc3-cosmos-init/plugins/packages/openc3-vue-common/src/tools/scriptrunner/ScriptRunner.vue [hunk 1]
```diff
@@ -1744,7 +1745,6 @@ export default {
         })
     },
     async scriptComplete() {
-      this.fatal = false
```
Comment (jmthomas) [inline openc3-cosmos-init/plugins/packages/openc3-vue-common/src/tools/scriptrunner/ScriptRunner.vue:1747]: We're no longer marking fatal lines ... the output shows which line is fatal and the script simply stops with the status set to 'Crashed'

File: openc3-cosmos-init/plugins/packages/openc3-vue-common/src/tools/scriptrunner/ScriptRunner.vue [hunk 2]
```diff
@@ -1755,8 +1755,10 @@ export default {
         this.subscription = null
       }
       this.receivedEvents.length = 0 // Clear any unprocessed events
-      // Ensure stopped, if the script has an error we don't get the server stopped message
-      this.state = 'stopped'
+      if (this.state === 'completed_errors') {
+        // Displaying 'Completed_errors' is not very user friendly
+        this.state = 'completed'
+      }
```
Comment (jmthomas) [inline openc3-cosmos-init/plugins/packages/openc3-vue-common/src/tools/scriptrunner/ScriptRunner.vue]: Rather than always setting to 'Stopped', we preserve the state unless 'completed_errors' which I just translate. The error will be in the script output.

File: openc3-cosmos-init/plugins/packages/openc3-vue-common/src/tools/scriptrunner/ScriptRunner.vue [hunk 3]
```diff
@@ -1966,6 +1956,15 @@ export default {
             }
           }
           break
+        case 'completed':
+        case 'completed_errors':
+        case 'stopped':
+        case 'crashed':
+        case 'killed':
```
Comment (jmthomas) [inline openc3-cosmos-init/plugins/packages/openc3-vue-common/src/tools/scriptrunner/ScriptRunner.vue:1981]: These are all the possible 'completed' states. The script is done in the backend.

File: openc3/lib/openc3/top_level.rb [hunk 4]
```diff
@@ -107,6 +106,8 @@ def self.add_to_search_path(path, front = true)
     end
   end
 
+  require 'openc3/utilities/logger'
```
Comment (jmthomas) [inline openc3/lib/openc3/top_level.rb:109]: Moving this fixes the circular dependency in Enterprise tests where `OpenC3.disable_warnings` is not defined.

File: openc3/python/openc3/utilities/running_script.py [hunk 5]
```diff
@@ -120,7 +120,6 @@ def _openc3_script_sleep(sleep_time=None):
 from openc3.tools.test_runner.test import SkipTestCase
 from openc3.script.suite import Group
 from openc3.utilities.script_instrumentor import ScriptInstrumentor
-import openc3.utilities.target_file_importer
```
Comment (jmthomas) [inline openc3/python/openc3/utilities/running_script.py:123]: not used

File: openc3/python/openc3/utilities/running_script.py [hunk 6]
```diff
@@ -148,37 +147,34 @@ def running_script_method(method, *args, **kwargs):
...
-            RunningScript.instance.perform_wait(
-                {"method": method, "id": prompt_id, "args": args, "kwargs": kwargs}
-            )
-            input = RunningScript.instance.user_input
+            RunningScript.instance.perform_wait({"method": method, "id": prompt_id, "args": args, "kwargs": kwargs})
+            user_input = RunningScript.instance.user_input
             # All ask and prompt dialogs should include a 'Cancel' button
             # If they cancel we wait so they can potentially stop
-            if input == "Cancel":
+            if user_input == "Cancel":
```
Comment (jmthomas) [inline openc3/python/openc3/utilities/running_script.py:154]: `input` shadows a built-in so renamed

File: openc3/python/openc3/utilities/running_script.py [hunk 7]
```diff
@@ -1073,7 +1060,6 @@ def run_thread_body(
                 kill_thread(self, RunningScript.output_thread)
                 RunningScript.output_thread = None
             self.mark_completed()
-            self.current_filename = None
```
Comment (jmthomas) [inline openc3/python/openc3/utilities/running_script.py:1076]: This is actually a bug because we're setting the `current_filename` method to None which basically removes it. I think any call to `RunningScript.instance.current_filename()` would crash after this. Maybe didn't matter because this is in Exception handling and we're already complete.

File: openc3/python/openc3/utilities/running_script.py [hunk 8]
```diff
@@ -1139,20 +1120,16 @@ def handle_exception(
...
             Logger.error("Error Connecting to Command and Telemetry Server")
         else:
-            formatted_lines = traceback.format_exception(
-                exc_type, exc_value, exc_traceback
-            )
-            Logger.error(formatted_lines[-1])  # Print the error itself
+            formatted_lines = traceback.format_exception(exc_type, exc_value, exc_traceback)
+            # Print the last 4 lines to show the exception, the ^^^^ line,
+            # the line itself, and the filename / line number
+            Logger.error("".join(formatted_lines[-4:]))
```
Comment (jmthomas) [inline openc3/python/openc3/utilities/running_script.py:1126]: Changed to show the actual line number of the exception. I noticed that previous we just print _only_ the exception which doesn't show where it is. Makes it a lot harder to debug.

File: openc3-cosmos-init/plugins/packages/openc3-vue-common/src/tools/scriptrunner/ScriptRunner.vue (hunk 2 above)
Comment (ryan-pratt) [reply openc3-cosmos-init/plugins/packages/openc3-vue-common/src/tools/scriptrunner/ScriptRunner.vue]: Couldn't this cause users to just see "completed" at the top and exit out without noticing the errors? I feel like there should be some sort of indication of errors where we display state. Maybe an alert icon, or shade it orange/yellow?

Comment (clayandgen) [reply openc3-cosmos-init/plugins/packages/openc3-vue-common/src/tools/scriptrunner/ScriptRunner.vue]: Execution Status remains with `completed_errors`, which is good. I do tend to agree that the UI should make it clear that the script did encounter errors.

**Comment by jmthomas** [comment]
Not sure if the reformatted was due to `pylance` or `black`. I think the former.

File: openc3-cosmos-init/plugins/packages/openc3-vue-common/src/tools/scriptrunner/ScriptRunner.vue (hunk 2 above)
Comment (jmthomas) [reply openc3-cosmos-init/plugins/packages/openc3-vue-common/src/tools/scriptrunner/ScriptRunner.vue]: The script still completed but it potentially had errors like Check Errors or even logical errors (divide by zero). The user clicked Retry or Go and the script completed. So I'm not sure what you mean by `exit out`. The status is in the script execution status. Perhaps we do textcolor changes of the status where completed_errors would display `Completed` but it would be orange. Crashed / Killed is red and all others green. Thoughts?

Comment (clayandgen) [reply openc3-cosmos-init/plugins/packages/openc3-vue-common/src/tools/scriptrunner/ScriptRunner.vue]: Can we make `completed_errors` state display in the UI as `Completed with Errors`? I feel like that's the most user-friendly.

Comment (jmthomas) [reply openc3-cosmos-init/plugins/packages/openc3-vue-common/src/tools/scriptrunner/ScriptRunner.vue]: That makes the State box _much_ wider to be readable

Comment (ryan-pratt) [reply openc3-cosmos-init/plugins/packages/openc3-vue-common/src/tools/scriptrunner/ScriptRunner.vue]: Could we add an alert icon or shade the box a color? Maybe also a tooltip, but that might not be necessary.

By "exit out," I mean leave the page (close the browser tab or navigate away)
