### PR TITLE
fix(anycable): prevent gRPC keepalive too_many_pings GoAway

### LINKED ISSUE #3240: anycable-go keepalive ping interval conflicts with gRPC minimum
### Describe the bug

The openc3-cosmos-script-runner-api container's anycable-go process sends gRPC keepalive pings to the Ruby RPC server every 30 seconds (the anycable-go default). The Ruby gRPC server enforces a minimum of 300 seconds between pings (the Go gRPC EnforcementPolicy.MinTime default). This mismatch causes periodic GoAway frames:
```
ERROR: [transport] Client received GoAway with error code ENHANCE_YOUR_CALM and debug data equal to ASCII "too_many_pings"
```

The GoAway tears down the internal gRPC connection. The gRPC client usually reconnects transparently, but when a GoAway coincides with an active RPC, the WebSocket connection to openc3cli drops and cli_script_monitor crashes with:
```
Error running script: unexpected end of input at line 1 column 1
Have you called 'script init'?
```

GoAway errors appear every ~30 seconds in every deployment. Most are survived, but over long suite runs the probability of a fatal collision with an active RPC approaches certainty.

Temporary Workaround Attempt: Mount a TOML config file at /src/anycable.toml in the script-runner-api container to increase the ping interval:
```
[rpc]
keepalive_ping_interval = 300
```
and:
```
  services:
    openc3-cosmos-script-runner-api:
      configs:
        - source: anycable-go-config
          target: /src/anycable.toml

  configs:
    anycable-go-config:
      content: |
        [rpc]
        keepalive_ping_interval = 300
```
This can be done via Docker Compose configs, without modifying the image. Fatal collisions seem to be reduced, but GoAway errors are still observed in logs.

This behavior was observed in Cosmos 6.7.0, but may be present in later versions with anycable-go v1.6.1.

### To Reproduce

1. Run any test suite that persists longer than 30 seconds via `docker compose exec ... openc3cli script run` (the docker compose exec method, where openc3cli connects via WebSocket to the already-running script-runner-api)
2. Check/grep script-runner-api container logs for `ENHANCE_YOUR_CALM` errors

### Expected behavior

`openc3cli script run` via `docker compose exec` should be able to run test suites of any duration without transport-layer failures. The internal gRPC keepalive configuration should not produce GoAway errors under normal operation.

### Screenshots

_No response_

### OS

Linux (Ubuntu 24.04 on headless CI systems, Arch/Manjaro on dev)

### OpenC3 COSMOS Version

6.7.0

### Browser

N/A

### PR DESCRIPTION
**Pull request by jmthomas**
AnyCable's default server min_recv_ping_interval_without_data_ms (10_000ms) matches anycable-go's hardcoded 10s client keepalive exactly. Jitter causes pings to arrive under the threshold, accumulating strikes and emitting GoAway ENHANCE_YOUR_CALM that tears down active RPCs (closes #3240). Halve the server minimum to 5_000ms for jitter tolerance.

### CODE REVIEW

File: openc3-cosmos-script-runner-api/config/initializers/anycable.rb [hunk 1]
```diff
@@ -0,0 +1,28 @@
...
+# exactly, so normal scheduling jitter can make a ping arrive just under the
+# threshold and accumulate strikes until the server emits
+# GoAway ENHANCE_YOUR_CALM "too_many_pings", tearing down active RPCs.
+# Halving the server minimum gives 5s of jitter tolerance against the fixed
+# 10s client interval. See grpc/grpc#25713 and doc/keepalive.md.
+AnyCable.configure do |config|
+  config.rpc_server_args = {
+    "grpc.keepalive_permit_without_calls" => 1,
+    "grpc.http2.min_recv_ping_interval_without_data_ms" => 5_000,
+    "grpc.http2.min_ping_interval_without_data_ms" => 5_000,
```
Comment (jmthomas) [inline openc3-cosmos-script-runner-api/config/initializers/anycable.rb:25]: Setting both of these to 60_000 allowed me to reproduce the issue. At least I could see the `ENHANCE_YOUR_CALM` message.

**Review by ryanmelt — APPROVED** [review]

**Comment by jmthomas** [comment]
Also made upstream fix in anycable-rb: https://github.com/anycable/anycable-rb/pull/6
