### PR TITLE
Data extractor wildcard merge treats array index brackets as glob patterns

### LINKED ISSUE #3258: Data Extractor wildcard merge treats array index brackets as glob patterns
When "Allow Wildcards" is enabled in Data Extractor, item names containing array indices (e.g. `ARY[0]`, `BRACKET[0]`) are incorrectly interpreted as glob character classes. `File.fnmatch("ARY[0]`", ...) treats `[0]` as a character class matching the single character `0`, so it matches `ARY0` instead of the literal item `ARY[0]`.

This affects any item name with brackets — both array index notation and items whose names literally contain brackets (like the demo's `BRACKET[0])`.

The bug is in `streaming_key.rb` where `has_glob?` uses `/[*?\[]/` to detect wildcards, and in `streaming_api.rb` where `File.fnmatch` is called without escaping literal brackets in the pattern.

### PR DESCRIPTION
**Pull request by mcosgriff**
## Summary

  - Distinguish array index brackets ([0], [12]) from glob character classes ([1-3], [A-C], [!0]) using a negative lookahead regex so items like ARY[0] pass through as literals while TEMP[1-3] expands as a glob
  - Escape array-index brackets before File.fnmatch calls in StreamingApi to prevent misinterpretation
  - Update frontend TargetPacketItemChooser.vue glob regex to match backend logic
  - Resolve SonarQube code quality issues in TargetPacketItemChooser.vue
  - Strip array index brackets before DB lookups, track indices per item, and extract the correct element after decoding the JSON array column. Also fix item_index alignment when available items are nil.

## Test plan

  - 20 new unit/integration tests added covering array index passthrough, bracket range expansion, star glob matching bracket items, LATEST + brackets, and packet glob + bracket items
  - All 99 specs pass (streaming_key_spec.rb + streaming_api_spec.rb)
  - ESLint passes with no warnings on openc3-vue-common
  - Manual test: subscribe to an item with array index (e.g. ARY[0]) in Data Extractor — should stream without glob expansion
  - Manual test: subscribe with bracket range glob (e.g. TEMP[1-3]) — should expand to TEMP1, TEMP2, TEMP3

Closes [#3258](https://github.com/OpenC3/cosmos/issues/3258)

### CODE REVIEW

File: openc3-cosmos-cmd-tlm-api/app/models/logged_streaming_thread.rb [hunk 1]
```diff
@@ -349,13 +353,17 @@ def stream_items(objects_by_topic, topics, offsets)
...
           topics: Set.new
         }
         meta = per_table[table_name]
         meta[:topics] << topic
 
         item = available[item_index]
-        next if item.nil? # API probably requested something that doesn't exist, so we'll ignore it and return nothing for it
+        if item.nil?
+          item_index += 1
+          next # API probably requested something that doesn't exist, so we'll ignore it and return nothing for it
```
Comment (jmthomas) [inline openc3-cosmos-cmd-tlm-api/app/models/logged_streaming_thread.rb:378]: Wow that's a nice bug ... how did we not hit that before?

**Review by jmthomas — COMMENTED** [review]
I see the Data Extractor -> Mode -> Allow Wildcards option now.

File: openc3-cosmos-cmd-tlm-api/app/models/logged_streaming_thread.rb (hunk 1 above)
Comment (ryan-pratt) [reply openc3-cosmos-cmd-tlm-api/app/models/logged_streaming_thread.rb:378]: Untested unhappy path... (Probably on me; that comment reads like I wrote it lol)

There probably isn't a way to hit this case unless you're writing custom code, which you'd be testing and just fix your API request when you hit this bug

**Review by jmthomas — APPROVED** [review]
Fix merge conflicts
