### PR TITLE
Script Authentication Enforced. Added Script Runner Ruby Client. 

### LINKED ISSUE #6: Script Api Authentication
Script API authentication is not working because $openc3_authenticate is not set.

### PR DESCRIPTION
**Pull request by ryanmelt**
Also Removed Long Delay API retries
closes #6

### CODE REVIEW

File: openc3-script-runner-api/config/routes.rb [hunk 1]
```diff
@@ -15,7 +15,6 @@
 
     get  "/running-script" => "running_script#index"
     get  "/running-script/:id" => "running_script#show"
-    post "/running-script/:id/start" => "running_script#start"
```
Comment (jmthomas) [inline openc3-script-runner-api/config/routes.rb:18]: How is it just this route is removed?

File: openc3/lib/openc3/io/json_api_object.rb [hunk 2]
```diff
@@ -77,14 +77,9 @@ def request(*method_params, **keyword_params)
...
-          @log = [nil, nil, nil]
-          connect() if !@http
-          response = _send_request(method: method, endpoint: endpoint, kwargs: kwargs)
-          return response unless response.code >= 500
-          sleep attempt
-        end
-        return nil
+        @log = [nil, nil, nil]
+        connect() if !@http
+        return _send_request(method: method, endpoint: endpoint, kwargs: kwargs)
```
Comment (jmthomas) [inline openc3/lib/openc3/io/json_api_object.rb:82]: Ahh, so this was the source the long delays .. especially with the sleep attempt in there!

File: openc3/lib/openc3/script/script_runner.rb [hunk 3]
```diff
@@ -0,0 +1,238 @@
...
+# attribution addendums as found in the LICENSE.txt
+#
+# This program is distributed in the hope that it will be useful,
+# but WITHOUT ANY WARRANTY; without even the implied warranty of
+# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+# GNU Affero General Public License for more details.
+
+module OpenC3
+  module Script
+    private
```
Comment (jmthomas) [inline openc3/lib/openc3/script/script_runner.rb:18]: Is this just a white list of allowed methods? Why is this necessary when it worked before (except without authentication)?

File: openc3/lib/openc3/io/json_drb_object.rb [hunk 4]
```diff
@@ -58,20 +58,18 @@ def initialize(url: ENV['OPENC3_API_URL'], timeout: 1.0, authentication: nil)
...
-          connect() if !@http
-          json_rpc_request = JsonRpcRequest.new(method_name, method_params, keyword_params, @id)
-          data = json_rpc_request.to_json(:allow_nan => true)
-          response_body = make_request(data: data)
-          if !response_body or response_body.to_s.length < 1
-            disconnect()
-          else
-            response = JsonRpcResponse.from_json(response_body)
-            return handle_response(response: response)
-          end
```
Comment (jmthomas) [inline openc3/lib/openc3/io/json_drb_object.rb:72]: No sleep delay in here ... why were we trying to retry here?

**Review by jmthomas — APPROVED** [review]
Where was the fix for the long delays? Was it the re

File: openc3-script-runner-api/config/routes.rb (hunk 1 above)
Comment (ryanmelt) [reply openc3-script-runner-api/config/routes.rb:18]: There is no running_script#start method.

File: openc3/lib/openc3/io/json_drb_object.rb (hunk 4 above)
Comment (ryanmelt) [reply openc3/lib/openc3/io/json_drb_object.rb:72]: The original COSMOS code had two attempts, in case the socket was broken by restarting the CmdTlmServer.   Not really relevant anymore and the sleep was really bad.  One of our junior engineers updated this.

File: openc3/lib/openc3/script/script_runner.rb (hunk 3 above)
Comment (ryanmelt) [reply openc3/lib/openc3/script/script_runner.rb:18]: This is new Ruby client code to spawn scripts and interact with them.  Before this code was only in Javascript.
