### PR TITLE
Calendar time

### LINKED ISSUE #3232: Calendar Time UI Bug
### Describe the bug

For reference, we have our server set to UTC time for all UI elements. However, in the calendar the time that it defaults to is still local time. When I try to create an event with the default, the tool (rightly) won't let me, so it's only a small visual bug. Somewhat related, I think it would be super helpful to have some kind of indication of the current time on the calendar, like how google calendar has a red line on the current date, as well as the time zone the calendar UI is operating in.

Image

### To Reproduce

1. Go to the admin tab and change Time Zone to UTC
2. Schedule a calendar timeline event and notice that it still defaults to local time

### Expected behavior

The calendar should default to the time zone specified in admin settings.

### Screenshots

_No response_

### OS

Ubuntu 24.04

### OpenC3 COSMOS Version

6.10.4

### Browser

Firefox, Chrome

### PR DESCRIPTION
**Pull request by jmthomas**
closes #3232

### CODE REVIEW

File: openc3-cosmos-init/plugins/packages/openc3-vue-common/src/util/settingsCache.js [hunk 1]
```diff
@@ -0,0 +1,53 @@
...
+
+export function getCachedSetting(name, fallback) {
+  if (cache.has(name)) {
+    return Promise.resolve(cache.get(name))
+  }
+  if (!inflight.has(name)) {
+    const promise = new OpenC3Api()
+      .get_setting(name)
+      .then((response) => {
+        const value = response || fallback
```
Comment (clayandgen) [inline openc3-cosmos-init/plugins/packages/openc3-vue-common/src/util/settingsCache.js]: `response ?? fallback` may be better, in case there's an actual setting with values like empty str or 0 so those don't trigger fallback

**Review by clayandgen — APPROVED** [review]

**Comment by clayandgen** [comment]
eslint on vuecommon, and sonarqube findings are worth looking at :)

File: openc3-cosmos-init/plugins/packages/openc3-vue-common/src/util/settingsCache.js (hunk 1 above)
Comment (jmthomas) [reply openc3-cosmos-init/plugins/packages/openc3-vue-common/src/util/settingsCache.js]: Good catch, fixed in the next push.

Comment (jmthomas) [reply openc3-cosmos-init/plugins/packages/openc3-vue-common/src/util/settingsCache.js]: Great comment!
