### PR TITLE
Fix graph time scale when there's no data to graph

### LINKED ISSUE #3165: TLM Grapher no data
### Describe the bug

TLM Grapher sets X axis to start at 1/1/1970 and shows no data

### To Reproduce

1. Go to Telemetry Grapher
2. Add an item that has data
3. Edit the graph
4. Set the start and end date/time to a region of time that does not have data for the item
5. Save

Second workflow:
1. Go to Telemetry Grapher
2. Add 2 items that have data
3. Edit the graph
4. Set the start and end date/time to a region of time that does not have data for just one of the items (the other has data during this period)
5. Save

### Expected behavior

X axis should be start-to-end time with no data
Maybe have a warning of "no data"
Data should be shown for any item(s) that do have data during the selected time

### Screenshots

Image

Image

Image

Image

### OS

_No response_

### OpenC3 COSMOS Version

7.0.0

### Browser

_No response_

### PR DESCRIPTION
**Pull request by ryan-pratt**
closes #3165

- changed `range` methods to arrow functions so that the `this` is correct
- replaced hardcoded default time range to instead show the previous hour
- check for the case when no data was returned, and set the x scale manually

**Case where no data exists (set range to 4/7/2025 to 5/7/2025):**
- x-axis now shows selected time range
- graph is empty, with an alert above indicating no data
image

**Case where data only exists for one of the items for part of the range:**
- did this by connecting the EXAMPLE target in the demo, graphing its PACKET_ID, and selecting a range around when I connected it
image

### CODE REVIEW

**Review by EmilyRagan — CHANGES_REQUESTED** [review]
This does cover some of the issues, but not all. The following steps produce a graph that is empty of data, which should have data. I think there is a backend component to the problem.

1. Have demo installed with history of data
2. Graph INST > HEALTH_STATUS > TEMP1
3. Install Fakesat
4. Add FAKESAT > HEALTH_STATUS > CPU_PWR to the graph
5. Wait a few minutes to have some data for this item showing on the graph
6. Uninstall Fakesat
7. Go back to TlmGrapher (graph should still have 2 items, shows live TEMP1 data)
    Screenshot 2026-04-09 at 9 40 55 AM
8. Edit graph to start 1 hour ago (end time optional, behavior is the same either way)

**EXPECTED**: TEMP1 data is shown for the past hour, CPU_PWR is shown for the few minutes that it had data (CPU_PWR shows no data would also be acceptable, as it is not currently installed, but showing the data that does exist would probably be preferred)
**ACTUAL**: Graph X axis is for last hour, but no data at all is shown on the graph - "messages" response on web socket was empty array after start time was changed, indicating back end problem with this request
Screenshot 2026-04-09 at 9 42 00 AM


cmd tlm server api error from docker logs:
```
{"time":1775741849847944964,"@timestamp":"2026-04-09T13:37:29.847944Z","level":"ERROR","microservice_name":"CMD__TLM__API","container_name":"b6e90135c0b4","message":"LoggedStreamingThread unexpectedly died\nNoMethodError : undefined method 'split' for nil\n/src/app/models/logged_streaming_thread.rb:359:in 'block (2 levels) in LoggedStreamingThread#stream_items'\n/src/app/models/logged_streaming_thread.rb:341:in 'Array#each'\n/src/app/models/logged_streaming_thread.rb:341:in 'block in LoggedStreamingThread#stream_items'\n/src/app/models/logged_streaming_thread.rb:338:in 'Hash#each'\n/src/app/models/logged_streaming_thread.rb:338:in 'LoggedStreamingThread#stream_items'\n/src/app/models/logged_streaming_thread.rb:134:in 'LoggedStreamingThread#tsdb_thread_body'\n/src/app/models/logged_streaming_thread.rb:55:in 'LoggedStreamingThread#thread_body'\n/src/app/models/streaming_thread.rb:40:in 'block in StreamingThread#start'","type":"log"}
```

File: openc3-cosmos-init/plugins/packages/openc3-vue-common/src/components/Graph.vue [hunk 1]
```diff
@@ -1148,6 +1148,14 @@ export default {
           max += 1
         }
         this.graph.setScale('x', { min, max })
+      } else if (this.graphStartDateTime && this.graphEndDateTime) {
+        const min = this.graphStartDateTime / 1_000_000_000
+        const max = this.graphEndDateTime / 1_000_000_000
+        this.graph.setScale('x', { min, max })
+        this.$notify.caution({
+          title: 'Empty graph data',
+          body: 'No data was returned for the selected time range.',
```
Comment (EmilyRagan) [inline openc3-cosmos-init/plugins/packages/openc3-vue-common/src/components/Graph.vue:1159]: We probably want this warning to show even if there is no end time selected but there is no data

**Comment by ryan-pratt** [comment]
> (CPU_PWR shows no data would also be acceptable, as it is not currently installed, but showing the data that does exist would probably be preferred)

Agreed, but I think it should just show no data for now as an 80/20 solution. Getting the streaming API to be able to stream data that does exist but isn't associated with a currently installed target/packet/item is going to be fairly involved I think, and outside the scope of this bug

**Review by jmthomas — APPROVED** [review]
