### PR TITLE
Include shard logic in networking

### LINKED ISSUE #1955: Include Shard Logic in Microservice Networking
**Describe the bug**
In a kubernetes-sharding scenario,
1) Each operator shard is given a deployment, but not a corresponding service to route microservice traffic.  
    In our own deployment, we use a similar for-loop to create one service per operator shard (conditionally, based on shard-ports defined in our values.yaml).  
    Since different microservices may run on different shards, we can't use a single service to point at all underlying deployments- services assume each pod is identical.
2) Traefik dynamic microservice networking does not utilize shard information
    Our scenario runs on kubernetes, but we're unable to dynamically create services/deployments per microservice. This is our usecase for requesting sharding.
    Conditional logic in `microservices_controller.rb` may need a rework to allow sharding information to be added.  
    My solution was to add something like this
    ```
        shard = microservice['shard']
        ...
        if ENV['SHARDING']
          url = "http://#{ENV['OPENC3_OPERATOR_HOSTNAME']}-#{shard}:#{port}"
    ```
   
**To Reproduce**
Deploy 3 operator shards.  
Deploy two different microservices hosting APIs on different shards.   
Create a corresponding service for each api hosting operator shard.
attempt to connect to `/[openc3-host]/[your-microservice-host]`.
Traefik would route traffic to OPENC3_OPERATOR_HOSTNAME, lacking shard information- probably `openc3-operator:[port]`, instead of `openc3-operator-[shard#]:[port]`

**Expected behavior**
- Shard information from microservice-model available to `microservices_controller.rb` when resolving traefik dynamic routes
- Kubernetes services corresponding to deployments when using sharding feature

**Environment (please complete the following information):**
- OS: All
- OpenC3 COSMOS Version 6.1.0
- Browser: All

### PR DESCRIPTION
**Pull request by jmthomas**
closes #1955

### CODE REVIEW

File: openc3-cosmos-cmd-tlm-api/app/controllers/microservices_controller.rb [hunk 1]
```diff
@@ -65,8 +65,13 @@ def traefik
       if prefix and ports[0][0]
         port = ports[0][0].to_i
         prefix = '/' + prefix unless prefix[0] == '/'
+        shard = microservice['shard'] || 0
         if ENV['OPENC3_OPERATOR_HOSTNAME']
-          url = "http://#{ENV['OPENC3_OPERATOR_HOSTNAME']}:#{port}"
+          if shard != 0
```
Comment (clayandgen) [inline openc3-cosmos-cmd-tlm-api/app/controllers/microservices_controller.rb:70]: Question here, when I deploy operator with 3 shards, the suffixes are `-0`, `-1`, `-2`.  I think with this change, shard 0 (the first shard) is not routable 🤔

Comment (jmthomas) [reply openc3-cosmos-cmd-tlm-api/app/controllers/microservices_controller.rb:70]: The default shard is 0 everywhere. I think that's why the logic is != 0. The default shard does not get the `-0` while all the rest do.

**Review by clayandgen — APPROVED** [review]
Verified with local k3d

  | Microservice    | Shard | URL Generated                 |
  |-----------------|-------|-------------------------------|
  | TEST_API_SHARD0 | 0     | http://openc3-operator:7778   |
  | TEST_API_SHARD1 | 1     | http://openc3-operator-1:7779 |
  | TEST_API_SHARD2 | 2     | http://openc3-operator-2:7780 |
